// Generated from Seguimiento egresos Musicala 2026.xlsx.
// Re-run extract_special_seed.mjs if the source workbook changes.
export const EGRESOS_ESPECIALES_SEED_META = {
  "workbook": "Seguimiento egresos Musicala 2026.xlsx",
  "collection": "seguimiento_egresos_especial",
  "generatedAt": "2026-07-03T16:25:38.387Z",
  "totalRows": 212
};

export const EGRESOS_ESPECIALES_SEED = [
  {
    "id": "categoria-arrendamiento-arrendamiento",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 1,
    "ordenCategoria": 1,
    "categoria": "Arrendamiento",
    "subcategoria": "Arrendamiento",
    "nombre": "Arrendamiento",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-salario-base",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 2,
    "ordenCategoria": 2,
    "categoria": "Nómina",
    "subcategoria": "Salario base",
    "nombre": "Salario base",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-auxilio-de-transporte",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 3,
    "ordenCategoria": 3,
    "categoria": "Nómina",
    "subcategoria": "Auxilio de transporte",
    "nombre": "Auxilio de transporte",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-bonificaciones",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 4,
    "ordenCategoria": 4,
    "categoria": "Nómina",
    "subcategoria": "Bonificaciones",
    "nombre": "Bonificaciones",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-cesantias",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 5,
    "ordenCategoria": 5,
    "categoria": "Nómina",
    "subcategoria": "Cesantías",
    "nombre": "Cesantías",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-intereses-de-cesantias",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 6,
    "ordenCategoria": 6,
    "categoria": "Nómina",
    "subcategoria": "Intereses de cesantías",
    "nombre": "Intereses de cesantías",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-primas",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 7,
    "ordenCategoria": 7,
    "categoria": "Nómina",
    "subcategoria": "Primas",
    "nombre": "Primas",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-miplanilla",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 8,
    "ordenCategoria": 8,
    "categoria": "Nómina",
    "subcategoria": "Miplanilla",
    "nombre": "Miplanilla",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-salud",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 9,
    "ordenCategoria": 9,
    "categoria": "Nómina",
    "subcategoria": "Salud",
    "nombre": "Salud",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-pension",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 10,
    "ordenCategoria": 10,
    "categoria": "Nómina",
    "subcategoria": "Pensión",
    "nombre": "Pensión",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-arl",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 11,
    "ordenCategoria": 11,
    "categoria": "Nómina",
    "subcategoria": "ARL",
    "nombre": "ARL",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-caja-de-compensacion",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 12,
    "ordenCategoria": 12,
    "categoria": "Nómina",
    "subcategoria": "Caja de compensación",
    "nombre": "Caja de compensación",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-intereses-por-mora",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 13,
    "ordenCategoria": 13,
    "categoria": "Nómina",
    "subcategoria": "Intereses por mora",
    "nombre": "Intereses por mora",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-dotacion",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 14,
    "ordenCategoria": 14,
    "categoria": "Nómina",
    "subcategoria": "Dotación",
    "nombre": "Dotación",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-incapacidades",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 15,
    "ordenCategoria": 15,
    "categoria": "Nómina",
    "subcategoria": "Incapacidades",
    "nombre": "Incapacidades",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-aporte-salud-empleado",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 16,
    "ordenCategoria": 16,
    "categoria": "Nómina",
    "subcategoria": "Aporte salud empleado",
    "nombre": "Aporte salud empleado",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-nomina-aporte-pension-empleado",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 17,
    "ordenCategoria": 17,
    "categoria": "Nómina",
    "subcategoria": "Aporte pensión empleado",
    "nombre": "Aporte pensión empleado",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-contabilidad-contabilidad",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 18,
    "ordenCategoria": 18,
    "categoria": "Contabilidad",
    "subcategoria": "Contabilidad",
    "nombre": "Contabilidad",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-aseo-implementos-de-aseo",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 19,
    "ordenCategoria": 19,
    "categoria": "Aseo",
    "subcategoria": "Implementos de aseo",
    "nombre": "Implementos de aseo",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-reparaciones-y-mantenimiento-jardineria",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 20,
    "ordenCategoria": 20,
    "categoria": "Reparaciones y mantenimiento",
    "subcategoria": "Jardinería",
    "nombre": "Jardinería",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-reparaciones-y-mantenimiento-tanque-de-agua",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 21,
    "ordenCategoria": 21,
    "categoria": "Reparaciones y mantenimiento",
    "subcategoria": "Tanque de agua",
    "nombre": "Tanque de agua",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-reparaciones-y-mantenimiento-persianas",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 22,
    "ordenCategoria": 22,
    "categoria": "Reparaciones y mantenimiento",
    "subcategoria": "Persianas",
    "nombre": "Persianas",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-reparaciones-y-mantenimiento-lamparas",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 23,
    "ordenCategoria": 23,
    "categoria": "Reparaciones y mantenimiento",
    "subcategoria": "Lámparas",
    "nombre": "Lámparas",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-reparaciones-y-mantenimiento-cojines-y-fundas",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 24,
    "ordenCategoria": 24,
    "categoria": "Reparaciones y mantenimiento",
    "subcategoria": "Cojines y fundas",
    "nombre": "Cojines y fundas",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-seguros-y-alarmas-vigilancia",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 25,
    "ordenCategoria": 25,
    "categoria": "Seguros y alarmas",
    "subcategoria": "Vigilancia",
    "nombre": "Vigilancia",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-seguros-y-alarmas-teleproteccion",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 26,
    "ordenCategoria": 26,
    "categoria": "Seguros y alarmas",
    "subcategoria": "Teleprotección",
    "nombre": "Teleprotección",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-seguros-y-alarmas-seguros",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 27,
    "ordenCategoria": 27,
    "categoria": "Seguros y alarmas",
    "subcategoria": "Seguros",
    "nombre": "Seguros",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-servicios-publicos-internet-movistar",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 28,
    "ordenCategoria": 28,
    "categoria": "Servicios públicos",
    "subcategoria": "Internet Movistar",
    "nombre": "Internet Movistar",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-servicios-publicos-enel-codensa",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 29,
    "ordenCategoria": 29,
    "categoria": "Servicios públicos",
    "subcategoria": "Enel Codensa",
    "nombre": "Enel Codensa",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-servicios-publicos-acueducto",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 30,
    "ordenCategoria": 30,
    "categoria": "Servicios públicos",
    "subcategoria": "Acueducto",
    "nombre": "Acueducto",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-servicios-publicos-celular-movistar-musicala",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 31,
    "ordenCategoria": 31,
    "categoria": "Servicios públicos",
    "subcategoria": "Celular Movistar Musicala",
    "nombre": "Celular Movistar Musicala",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-servicios-publicos-celular-movistar-alek",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 32,
    "ordenCategoria": 32,
    "categoria": "Servicios públicos",
    "subcategoria": "Celular Movistar Alek",
    "nombre": "Celular Movistar Alek",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-servicios-publicos-celular-movistar-cata",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 33,
    "ordenCategoria": 33,
    "categoria": "Servicios públicos",
    "subcategoria": "Celular Movistar Cata",
    "nombre": "Celular Movistar Cata",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-sg-sst-one-soluciones",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 34,
    "ordenCategoria": 34,
    "categoria": "SG SST",
    "subcategoria": "One Soluciones",
    "nombre": "One Soluciones",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-software-y-plataformas-digitales-wix",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 35,
    "ordenCategoria": 35,
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Wix",
    "nombre": "Wix",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-software-y-plataformas-digitales-dominio",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 36,
    "ordenCategoria": 36,
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Dominio",
    "nombre": "Dominio",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-software-y-plataformas-digitales-google-one-alek",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 37,
    "ordenCategoria": 37,
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Google One Alek",
    "nombre": "Google One Alek",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-software-y-plataformas-digitales-google-one-cata",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 38,
    "ordenCategoria": 38,
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Google One Cata",
    "nombre": "Google One Cata",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-software-y-plataformas-digitales-google-one-musicala",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 39,
    "ordenCategoria": 39,
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Google One Musicala",
    "nombre": "Google One Musicala",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-software-y-plataformas-digitales-zoom",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 40,
    "ordenCategoria": 40,
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Zoom",
    "nombre": "Zoom",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-software-y-plataformas-digitales-chatgpt",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 41,
    "ordenCategoria": 41,
    "categoria": "Software y plataformas digitales",
    "subcategoria": "ChatGPT",
    "nombre": "ChatGPT",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-software-y-plataformas-digitales-spotify",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 42,
    "ordenCategoria": 42,
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Spotify",
    "nombre": "Spotify",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-software-y-plataformas-digitales-netflix",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 43,
    "ordenCategoria": 43,
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Netflix",
    "nombre": "Netflix",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-software-y-plataformas-digitales-disney",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 44,
    "ordenCategoria": 44,
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Disney+",
    "nombre": "Disney+",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-software-y-plataformas-digitales-star",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 45,
    "ordenCategoria": 45,
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Star+",
    "nombre": "Star+",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-software-y-plataformas-digitales-keybe",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 46,
    "ordenCategoria": 46,
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Keybe",
    "nombre": "Keybe",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-bancarios-cuota-de-manejo-bancolombia",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 47,
    "ordenCategoria": 47,
    "categoria": "Bancarios",
    "subcategoria": "Cuota de manejo Bancolombia",
    "nombre": "Cuota de manejo Bancolombia",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-bancarios-cuota-de-manejo-davivienda",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 48,
    "ordenCategoria": 48,
    "categoria": "Bancarios",
    "subcategoria": "Cuota de manejo Davivienda",
    "nombre": "Cuota de manejo Davivienda",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-bancarios-comisiones-de-pago",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 49,
    "ordenCategoria": 49,
    "categoria": "Bancarios",
    "subcategoria": "Comisiones de pago",
    "nombre": "Comisiones de pago",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-bancarios-comisiones-de-email",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 50,
    "ordenCategoria": 50,
    "categoria": "Bancarios",
    "subcategoria": "Comisiones de email",
    "nombre": "Comisiones de email",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-bancarios-comision-bold",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 51,
    "ordenCategoria": 51,
    "categoria": "Bancarios",
    "subcategoria": "Comisión Bold",
    "nombre": "Comisión Bold",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-bancarios-comision-nequi",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 52,
    "ordenCategoria": 52,
    "categoria": "Bancarios",
    "subcategoria": "Comisión Nequi",
    "nombre": "Comisión Nequi",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-bancarios-tarjeta-de-credito",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 53,
    "ordenCategoria": 53,
    "categoria": "Bancarios",
    "subcategoria": "Tarjeta de crédito",
    "nombre": "Tarjeta de crédito",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-creditos-y-prestamos-credito-de-libre-inversion",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 54,
    "ordenCategoria": 54,
    "categoria": "Créditos y Préstamos",
    "subcategoria": "Crédito de libre inversión",
    "nombre": "Crédito de libre inversión",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-creditos-y-prestamos-prestamo-sumetlum",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 55,
    "ordenCategoria": 55,
    "categoria": "Créditos y Préstamos",
    "subcategoria": "Préstamo Sumetlum",
    "nombre": "Préstamo Sumetlum",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-creditos-y-prestamos-transferencia-musicala",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 56,
    "ordenCategoria": 56,
    "categoria": "Créditos y Préstamos",
    "subcategoria": "Transferencia Musicala",
    "nombre": "Transferencia Musicala",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-licencias-bomberos",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 57,
    "ordenCategoria": 57,
    "categoria": "Licencias",
    "subcategoria": "Bomberos",
    "nombre": "Bomberos",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-licencias-sayco",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 58,
    "ordenCategoria": 58,
    "categoria": "Licencias",
    "subcategoria": "SAYCO",
    "nombre": "SAYCO",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-impuestos-predial-etc-impuesto-4x1000",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 59,
    "ordenCategoria": 59,
    "categoria": "Impuestos (predial, etc.)",
    "subcategoria": "Impuesto 4x1000",
    "nombre": "Impuesto 4x1000",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-impuestos-predial-etc-impuesto-iva",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 60,
    "ordenCategoria": 60,
    "categoria": "Impuestos (predial, etc.)",
    "subcategoria": "Impuesto IVA",
    "nombre": "Impuesto IVA",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-impuestos-predial-etc-impuesto-reteica",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 61,
    "ordenCategoria": 61,
    "categoria": "Impuestos (predial, etc.)",
    "subcategoria": "Impuesto Reteica",
    "nombre": "Impuesto Reteica",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-impuestos-predial-etc-impuesto-retefuente",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 62,
    "ordenCategoria": 62,
    "categoria": "Impuestos (predial, etc.)",
    "subcategoria": "Impuesto Retefuente",
    "nombre": "Impuesto Retefuente",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-impuestos-predial-etc-ica",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 63,
    "ordenCategoria": 63,
    "categoria": "Impuestos (predial, etc.)",
    "subcategoria": "ICA",
    "nombre": "ICA",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-impuestos-predial-etc-declaracion-de-renta",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 64,
    "ordenCategoria": 64,
    "categoria": "Impuestos (predial, etc.)",
    "subcategoria": "Declaración de renta",
    "nombre": "Declaración de renta",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-pago-proveedores-pago-proveedores",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 65,
    "ordenCategoria": 65,
    "categoria": "Pago Proveedores",
    "subcategoria": "Pago Proveedores",
    "nombre": "Pago Proveedores",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-diseno-y-publicidad-diseno-grafico",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 66,
    "ordenCategoria": 66,
    "categoria": "Diseño y publicidad",
    "subcategoria": "Diseño gráfico",
    "nombre": "Diseño gráfico",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-diseno-y-publicidad-publicidad",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 67,
    "ordenCategoria": 67,
    "categoria": "Diseño y publicidad",
    "subcategoria": "Publicidad",
    "nombre": "Publicidad",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-diseno-y-publicidad-marketing",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 68,
    "ordenCategoria": 68,
    "categoria": "Diseño y publicidad",
    "subcategoria": "Marketing",
    "nombre": "Marketing",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-diseno-y-publicidad-google-ads",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 69,
    "ordenCategoria": 69,
    "categoria": "Diseño y publicidad",
    "subcategoria": "Google Ads",
    "nombre": "Google Ads",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-diseno-y-publicidad-tik-tok",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 70,
    "ordenCategoria": 70,
    "categoria": "Diseño y publicidad",
    "subcategoria": "Tik Tok",
    "nombre": "Tik Tok",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-diseno-y-publicidad-facebook",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 71,
    "ordenCategoria": 71,
    "categoria": "Diseño y publicidad",
    "subcategoria": "Facebook",
    "nombre": "Facebook",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-diseno-y-publicidad-community-manager",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 72,
    "ordenCategoria": 72,
    "categoria": "Diseño y publicidad",
    "subcategoria": "Community manager",
    "nombre": "Community manager",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-transporte-transporte",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 73,
    "ordenCategoria": 73,
    "categoria": "Transporte",
    "subcategoria": "Transporte",
    "nombre": "Transporte",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-legal-legal",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 74,
    "ordenCategoria": 74,
    "categoria": "Legal",
    "subcategoria": "Legal",
    "nombre": "Legal",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-reclutamiento-reclutamiento",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 75,
    "ordenCategoria": 75,
    "categoria": "Reclutamiento",
    "subcategoria": "Reclutamiento",
    "nombre": "Reclutamiento",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-instrumentos-y-equipos-instrumentos-y-equipos",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 76,
    "ordenCategoria": 76,
    "categoria": "Instrumentos y equipos",
    "subcategoria": "Instrumentos y equipos",
    "nombre": "Instrumentos y equipos",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-herramientas-audiovisuales-herramientas-audiovisuales",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 77,
    "ordenCategoria": 77,
    "categoria": "Herramientas audiovisuales",
    "subcategoria": "Herramientas audiovisuales",
    "nombre": "Herramientas audiovisuales",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-acustica-acustica",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 78,
    "ordenCategoria": 78,
    "categoria": "Acústica",
    "subcategoria": "Acústica",
    "nombre": "Acústica",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-salarios-docentes-prestacion-bonificacion-profesor",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 79,
    "ordenCategoria": 79,
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Bonificación Profesor",
    "nombre": "Bonificación Profesor",
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-otros-gastos-especifique-otros-gastos",
    "tipoRegistro": "categoria",
    "origenHoja": "Parámetros",
    "ordenGlobal": 80,
    "ordenCategoria": 80,
    "categoria": "Otros gastos (especifique)",
    "subcategoria": "Otros gastos",
    "nombre": "Otros gastos",
    "activo": true,
    "visible": true
  },
  {
    "id": "equipo_directo-andrea-catalina-medina-leal",
    "tipoRegistro": "equipo_directo",
    "origenHoja": "Parámetros",
    "ordenGlobal": 81,
    "ordenCategoria": 1,
    "categoria": "Equipo directo",
    "subcategoria": "Andrea Catalina Medina Leal",
    "nombre": "Andrea Catalina Medina Leal",
    "activo": true,
    "visible": true
  },
  {
    "id": "equipo_directo-jimmy-alexander-caballero-moreno",
    "tipoRegistro": "equipo_directo",
    "origenHoja": "Parámetros",
    "ordenGlobal": 82,
    "ordenCategoria": 2,
    "categoria": "Equipo directo",
    "subcategoria": "Jimmy Alexander Caballero Moreno",
    "nombre": "Jimmy Alexander Caballero Moreno",
    "activo": true,
    "visible": true
  },
  {
    "id": "equipo_directo-angie-camila-rodriguez-torres",
    "tipoRegistro": "equipo_directo",
    "origenHoja": "Parámetros",
    "ordenGlobal": 83,
    "ordenCategoria": 3,
    "categoria": "Equipo directo",
    "subcategoria": "Angie Camila Rodríguez Torres",
    "nombre": "Angie Camila Rodríguez Torres",
    "activo": true,
    "visible": true
  },
  {
    "id": "equipo_directo-natalia-alarcon",
    "tipoRegistro": "equipo_directo",
    "origenHoja": "Parámetros",
    "ordenGlobal": 84,
    "ordenCategoria": 4,
    "categoria": "Equipo directo",
    "subcategoria": "Natalia Alarcón",
    "nombre": "Natalia Alarcón",
    "activo": true,
    "visible": true
  },
  {
    "id": "equipo_directo-emily-bejarano",
    "tipoRegistro": "equipo_directo",
    "origenHoja": "Parámetros",
    "ordenGlobal": 85,
    "ordenCategoria": 5,
    "categoria": "Equipo directo",
    "subcategoria": "Emily Bejarano",
    "nombre": "Emily Bejarano",
    "activo": true,
    "visible": true
  },
  {
    "id": "equipo_directo-laura-sanchez",
    "tipoRegistro": "equipo_directo",
    "origenHoja": "Parámetros",
    "ordenGlobal": 86,
    "ordenCategoria": 6,
    "categoria": "Equipo directo",
    "subcategoria": "Laura Sánchez",
    "nombre": "Laura Sánchez",
    "activo": true,
    "visible": true
  },
  {
    "id": "equipo_directo-thalia-sarmiento",
    "tipoRegistro": "equipo_directo",
    "origenHoja": "Parámetros",
    "ordenGlobal": 87,
    "ordenCategoria": 7,
    "categoria": "Equipo directo",
    "subcategoria": "Thalia Sarmiento",
    "nombre": "Thalia Sarmiento",
    "activo": true,
    "visible": true
  },
  {
    "id": "equipo_directo-brenda-tatiana-giraldo-leyton",
    "tipoRegistro": "equipo_directo",
    "origenHoja": "Parámetros",
    "ordenGlobal": 88,
    "ordenCategoria": 8,
    "categoria": "Equipo directo",
    "subcategoria": "Brenda Tatiana Giraldo Leyton",
    "nombre": "Brenda Tatiana Giraldo Leyton",
    "activo": true,
    "visible": true
  },
  {
    "id": "equipo_directo-yusting-camila-granados-cortes",
    "tipoRegistro": "equipo_directo",
    "origenHoja": "Parámetros",
    "ordenGlobal": 89,
    "ordenCategoria": 9,
    "categoria": "Equipo directo",
    "subcategoria": "Yusting Camila Granados Cortés",
    "nombre": "Yusting Camila Granados Cortés",
    "activo": true,
    "visible": true
  },
  {
    "id": "equipo_directo-daniela-camelo-arevalo",
    "tipoRegistro": "equipo_directo",
    "origenHoja": "Parámetros",
    "ordenGlobal": 90,
    "ordenCategoria": 10,
    "categoria": "Equipo directo",
    "subcategoria": "Daniela Camelo Arévalo",
    "nombre": "Daniela Camelo Arévalo",
    "activo": true,
    "visible": true
  },
  {
    "id": "equipo_directo-leydy-jhoana-diaz-salas",
    "tipoRegistro": "equipo_directo",
    "origenHoja": "Parámetros",
    "ordenGlobal": 91,
    "ordenCategoria": 11,
    "categoria": "Equipo directo",
    "subcategoria": "Leydy Jhoana Díaz Salas",
    "nombre": "Leydy Jhoana Díaz Salas",
    "activo": true,
    "visible": true
  },
  {
    "id": "equipo_directo-maria-camila-pirajan-gutierrez",
    "tipoRegistro": "equipo_directo",
    "origenHoja": "Parámetros",
    "ordenGlobal": 92,
    "ordenCategoria": 12,
    "categoria": "Equipo directo",
    "subcategoria": "Maria Camila Pirajan Gutiérrez",
    "nombre": "Maria Camila Pirajan Gutiérrez",
    "activo": true,
    "visible": true
  },
  {
    "id": "equipo_directo-santiago-gutierrez-fonseca",
    "tipoRegistro": "equipo_directo",
    "origenHoja": "Parámetros",
    "ordenGlobal": 93,
    "ordenCategoria": 13,
    "categoria": "Equipo directo",
    "subcategoria": "Santiago Gutierrez Fonseca",
    "nombre": "Santiago Gutierrez Fonseca",
    "activo": true,
    "visible": true
  },
  {
    "id": "medio_pago-efectivo",
    "tipoRegistro": "medio_pago",
    "origenHoja": "Parámetros",
    "ordenGlobal": 94,
    "ordenCategoria": 1,
    "categoria": "Medio de pago",
    "subcategoria": "Efectivo",
    "nombre": "Efectivo",
    "activo": true,
    "visible": true
  },
  {
    "id": "medio_pago-bancolombia-m",
    "tipoRegistro": "medio_pago",
    "origenHoja": "Parámetros",
    "ordenGlobal": 95,
    "ordenCategoria": 2,
    "categoria": "Medio de pago",
    "subcategoria": "Bancolombia M",
    "nombre": "Bancolombia M",
    "activo": true,
    "visible": true
  },
  {
    "id": "medio_pago-davivienda-m",
    "tipoRegistro": "medio_pago",
    "origenHoja": "Parámetros",
    "ordenGlobal": 96,
    "ordenCategoria": 3,
    "categoria": "Medio de pago",
    "subcategoria": "Davivienda M",
    "nombre": "Davivienda M",
    "activo": true,
    "visible": true
  },
  {
    "id": "medio_pago-bold",
    "tipoRegistro": "medio_pago",
    "origenHoja": "Parámetros",
    "ordenGlobal": 97,
    "ordenCategoria": 4,
    "categoria": "Medio de pago",
    "subcategoria": "Bold",
    "nombre": "Bold",
    "activo": true,
    "visible": true
  },
  {
    "id": "medio_pago-nequi",
    "tipoRegistro": "medio_pago",
    "origenHoja": "Parámetros",
    "ordenGlobal": 98,
    "ordenCategoria": 5,
    "categoria": "Medio de pago",
    "subcategoria": "Nequi",
    "nombre": "Nequi",
    "activo": true,
    "visible": true
  },
  {
    "id": "medio_pago-tarjeta-de-credito",
    "tipoRegistro": "medio_pago",
    "origenHoja": "Parámetros",
    "ordenGlobal": 99,
    "ordenCategoria": 6,
    "categoria": "Medio de pago",
    "subcategoria": "Tarjeta de crédito",
    "nombre": "Tarjeta de crédito",
    "activo": true,
    "visible": true
  },
  {
    "id": "medio_pago-transferencia",
    "tipoRegistro": "medio_pago",
    "origenHoja": "Parámetros",
    "ordenGlobal": 100,
    "ordenCategoria": 7,
    "categoria": "Medio de pago",
    "subcategoria": "Transferencia",
    "nombre": "Transferencia",
    "activo": true,
    "visible": true
  },
  {
    "id": "proyecto-musicala",
    "tipoRegistro": "proyecto",
    "origenHoja": "Parámetros",
    "ordenGlobal": 101,
    "ordenCategoria": 1,
    "categoria": "Proyectos",
    "subcategoria": "Musicala",
    "nombre": "Musicala",
    "activo": true,
    "visible": true
  },
  {
    "id": "proyecto-fsa",
    "tipoRegistro": "proyecto",
    "origenHoja": "Parámetros",
    "ordenGlobal": 102,
    "ordenCategoria": 2,
    "categoria": "Proyectos",
    "subcategoria": "FSA",
    "nombre": "FSA",
    "activo": true,
    "visible": true
  },
  {
    "id": "proyecto-musicafe",
    "tipoRegistro": "proyecto",
    "origenHoja": "Parámetros",
    "ordenGlobal": 103,
    "ordenCategoria": 3,
    "categoria": "Proyectos",
    "subcategoria": "Musicafé",
    "nombre": "Musicafé",
    "activo": true,
    "visible": true
  },
  {
    "id": "proyecto-eventos",
    "tipoRegistro": "proyecto",
    "origenHoja": "Parámetros",
    "ordenGlobal": 104,
    "ordenCategoria": 4,
    "categoria": "Proyectos",
    "subcategoria": "Eventos",
    "nombre": "Eventos",
    "activo": true,
    "visible": true
  },
  {
    "id": "gasto-fijo-2-cuota-bancolombia",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-d77e295a-c37c-46ec-a792-4f466b6f0a6d",
    "ordenGlobal": 105,
    "nombre": "Cuota Bancolombia",
    "obligacion": "Cuota Bancolombia",
    "categoria": "Bancarios",
    "subcategoria": "Cuota de manejo Bancolombia",
    "frecuencia": "Mensual",
    "diaSugerido": 5,
    "valorSugerido": 55472,
    "proveedor": "Bancolombia",
    "automatico": true,
    "cuentaBancaria": "Bancolombia M",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-3-cuota-davivienda",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-2c00a710-ee6d-4bed-b154-e23dd92f42b4",
    "ordenGlobal": 106,
    "nombre": "Cuota Davivienda",
    "obligacion": "Cuota Davivienda",
    "categoria": "Bancarios",
    "subcategoria": "Cuota de manejo Davivienda",
    "frecuencia": "Mensual",
    "diaSugerido": 5,
    "valorSugerido": 6800,
    "proveedor": "Davivienda",
    "automatico": true,
    "cuentaBancaria": "Davivienda M",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-4-contabilidad",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-a6e697f6-6aa9-4549-8cb1-d7f19988cd6d",
    "ordenGlobal": 107,
    "nombre": "Contabilidad",
    "obligacion": "Contabilidad",
    "categoria": "Contabilidad",
    "subcategoria": "Contabilidad",
    "frecuencia": "Mensual",
    "diaSugerido": 1,
    "valorSugerido": 1100000,
    "proveedor": "In-plementar",
    "automatico": false,
    "cuentaBancaria": "Bancolombia M",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "0.04",
    "retencionIca": "0.0077",
    "visible": true
  },
  {
    "id": "categoria-licencias-registro-mercantil-ccb",
    "tipoRegistro": "categoria",
    "origenHoja": "Gastos fijos",
    "ordenGlobal": 108,
    "ordenCategoria": 1003,
    "categoria": "Licencias",
    "subcategoria": "Registro mercantil CCB",
    "nombre": "Registro mercantil CCB",
    "activo": true,
    "visible": true
  },
  {
    "id": "gasto-fijo-5-registro-mercantil-ccb",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-cdf9203f-0f83-4e68-af8e-b3b4797d51f1",
    "ordenGlobal": 109,
    "nombre": "Registro mercantil CCB",
    "obligacion": "Registro mercantil CCB",
    "categoria": "Licencias",
    "subcategoria": "Registro mercantil CCB",
    "frecuencia": "Anual",
    "diaSugerido": null,
    "valorSugerido": 831900,
    "proveedor": "CCB",
    "automatico": false,
    "cuentaBancaria": "Bancolombia M",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-6-jardineria",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-17e0420e-f1a6-4eb6-ac7e-f6c3c76c3d8d",
    "ordenGlobal": 110,
    "nombre": "Jardinería",
    "obligacion": "Jardinería",
    "categoria": "Reparaciones y mantenimiento",
    "subcategoria": "Jardinería",
    "frecuencia": "Mensual",
    "diaSugerido": 5,
    "valorSugerido": 25000,
    "proveedor": "Antonio Camargo",
    "automatico": false,
    "cuentaBancaria": "Efectivo",
    "activo": true,
    "proyecto": "Sede Pasadena",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-7-lavado-de-tanque",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-281252dd-ff40-40ab-82e1-3d71b577157e",
    "ordenGlobal": 111,
    "nombre": "Lavado de tanque",
    "obligacion": "Lavado de tanque",
    "categoria": "Reparaciones y mantenimiento",
    "subcategoria": "Tanque de agua",
    "frecuencia": "Semestral",
    "diaSugerido": 46147,
    "valorSugerido": 273700,
    "proveedor": "IF PLANING SAS",
    "automatico": false,
    "cuentaBancaria": "Davivienda",
    "activo": true,
    "proyecto": "Sede Pasadena",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "categoria-reparaciones-y-mantenimiento-recarga-de-extintores",
    "tipoRegistro": "categoria",
    "origenHoja": "Gastos fijos",
    "ordenGlobal": 112,
    "ordenCategoria": 1006,
    "categoria": "Reparaciones y mantenimiento",
    "subcategoria": "Recarga de extintores",
    "nombre": "Recarga de extintores",
    "activo": true,
    "visible": true
  },
  {
    "id": "gasto-fijo-8-mantenimiento-de-extintores",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-97b691bd-1c64-4ae2-b332-d667a71d4fe3",
    "ordenGlobal": 113,
    "nombre": "Mantenimiento de extintores",
    "obligacion": "Mantenimiento de extintores",
    "categoria": "Reparaciones y mantenimiento",
    "subcategoria": "Recarga de extintores",
    "frecuencia": "Anual",
    "diaSugerido": null,
    "valorSugerido": 95000,
    "proveedor": "EXTINTORES DISTRIBUIDOS DE FABRICA S A S",
    "automatico": false,
    "cuentaBancaria": "",
    "activo": true,
    "proyecto": "Sede Pasadena",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-9-teleproteccion",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-d21371e1-04a8-48fc-85f4-205224707847",
    "ordenGlobal": 114,
    "nombre": "Teleprotección",
    "obligacion": "Teleprotección",
    "categoria": "Seguros y alarmas",
    "subcategoria": "Teleprotección",
    "frecuencia": "Mensual",
    "diaSugerido": 9,
    "valorSugerido": 159815,
    "proveedor": "Teleprotección",
    "automatico": false,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Sede Pasadena",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "categoria-servicios-generales-aseo",
    "tipoRegistro": "categoria",
    "origenHoja": "Gastos fijos",
    "ordenGlobal": 115,
    "ordenCategoria": 1008,
    "categoria": "Servicios generales",
    "subcategoria": "Aseo",
    "nombre": "Aseo",
    "activo": true,
    "visible": true
  },
  {
    "id": "gasto-fijo-10-pago-proveedores",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-bb3c7b6b-90eb-4e79-af02-48a8445e3320",
    "ordenGlobal": 116,
    "nombre": "Pago proveedores",
    "obligacion": "Pago proveedores",
    "categoria": "Servicios generales",
    "subcategoria": "Aseo",
    "frecuencia": "Mensual",
    "diaSugerido": 1,
    "valorSugerido": 975000,
    "proveedor": "Nancy Caballero Moreno",
    "automatico": false,
    "cuentaBancaria": "Bancolombia M",
    "activo": true,
    "proyecto": "Sede Pasadena",
    "retefuenteServicios": "",
    "retencionIca": "0.0097",
    "visible": true
  },
  {
    "id": "gasto-fijo-11-internet",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-623f553e-3291-498f-85c9-f03a09746e61",
    "ordenGlobal": 117,
    "nombre": "Internet",
    "obligacion": "Internet",
    "categoria": "Servicios públicos",
    "subcategoria": "Internet Movistar",
    "frecuencia": "Mensual",
    "diaSugerido": 10,
    "valorSugerido": 140080,
    "proveedor": "Movistar",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Sede Pasadena",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-12-celular-musicala",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-1bd1d44a-0227-42cc-834e-511ea95d2a89",
    "ordenGlobal": 118,
    "nombre": "Celular Musicala",
    "obligacion": "Celular Musicala",
    "categoria": "Servicios públicos",
    "subcategoria": "Celular Movistar Musicala",
    "frecuencia": "Mensual",
    "diaSugerido": 12,
    "valorSugerido": 45990,
    "proveedor": "Movistar",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-13-celular-movistar-cata",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-7fcfdee3-6548-4670-a765-17703ff88d96",
    "ordenGlobal": 119,
    "nombre": "Celular Movistar Cata",
    "obligacion": "Celular Movistar Cata",
    "categoria": "Servicios públicos",
    "subcategoria": "Celular Movistar Musicala",
    "frecuencia": "Mensual",
    "diaSugerido": 15,
    "valorSugerido": 45990,
    "proveedor": "Movistar",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-14-celular-movistar-alek",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-5782966a-7a59-4653-88c2-f29247e193cb",
    "ordenGlobal": 120,
    "nombre": "Celular Movistar Alek",
    "obligacion": "Celular Movistar Alek",
    "categoria": "Servicios públicos",
    "subcategoria": "Celular Movistar Musicala",
    "frecuencia": "Mensual",
    "diaSugerido": 15,
    "valorSugerido": 45990,
    "proveedor": "Movistar",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-15-enel-codensa",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-f872f5ba-d7af-42b4-b02d-2d1a561f9713",
    "ordenGlobal": 121,
    "nombre": "Enel Codensa",
    "obligacion": "Enel Codensa",
    "categoria": "Servicios públicos",
    "subcategoria": "Enel Codensa",
    "frecuencia": "Mensual",
    "diaSugerido": 1,
    "valorSugerido": 400000,
    "proveedor": "Enel Codensa",
    "automatico": true,
    "cuentaBancaria": "Davivienda M",
    "activo": true,
    "proyecto": "Sede Pasadena",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-16-acueducto",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-eea21775-f07b-4a82-9293-3876ed303803",
    "ordenGlobal": 122,
    "nombre": "Acueducto",
    "obligacion": "Acueducto",
    "categoria": "Servicios públicos",
    "subcategoria": "Acueducto",
    "frecuencia": "Bimensual",
    "diaSugerido": 1,
    "valorSugerido": 200000,
    "proveedor": "Acueducto",
    "automatico": false,
    "cuentaBancaria": "Davivienda M",
    "activo": true,
    "proyecto": "Sede Pasadena",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "categoria-sg-sst-safe-mode",
    "tipoRegistro": "categoria",
    "origenHoja": "Gastos fijos",
    "ordenGlobal": 123,
    "ordenCategoria": 1015,
    "categoria": "SG SST",
    "subcategoria": "Safe Mode",
    "nombre": "Safe Mode",
    "activo": true,
    "visible": true
  },
  {
    "id": "gasto-fijo-17-sg-sst",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-a8d74bdc-d4cc-4b47-8493-39608d0186ed",
    "ordenGlobal": 124,
    "nombre": "SG-SST",
    "obligacion": "SG-SST",
    "categoria": "SG SST",
    "subcategoria": "Safe Mode",
    "frecuencia": "Mensual",
    "diaSugerido": 1,
    "valorSugerido": 446250,
    "proveedor": "Safe Mode SAS",
    "automatico": false,
    "cuentaBancaria": "Bancolombia M",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "0",
    "retencionIca": "0.15",
    "visible": true
  },
  {
    "id": "gasto-fijo-18-spotify",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-d74e61ca-6b83-4664-8ab9-31d4be751628",
    "ordenGlobal": 125,
    "nombre": "Spotify",
    "obligacion": "Spotify",
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Spotify",
    "frecuencia": "Mensual",
    "diaSugerido": 23,
    "valorSugerido": 26400,
    "proveedor": "Spotify",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-19-disney",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-1fc42e6e-50fc-4b08-a878-9c7fd529b487",
    "ordenGlobal": 126,
    "nombre": "Disney+",
    "obligacion": "Disney+",
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Disney+",
    "frecuencia": "Mensual",
    "diaSugerido": 16,
    "valorSugerido": 34900,
    "proveedor": "Disney+",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-20-netflix",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-87cce236-bd30-4c6d-b7fe-6312c7f43bb0",
    "ordenGlobal": 127,
    "nombre": "Netflix",
    "obligacion": "Netflix",
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Netflix",
    "frecuencia": "Mensual",
    "diaSugerido": 30,
    "valorSugerido": 44900,
    "proveedor": "Netflix",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-21-chatgpt",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-f8438d79-4c2e-44c4-85b2-9a546fea8728",
    "ordenGlobal": 128,
    "nombre": "ChatGPT",
    "obligacion": "ChatGPT",
    "categoria": "Software y plataformas digitales",
    "subcategoria": "ChatGPT",
    "frecuencia": "Mensual",
    "diaSugerido": 5,
    "valorSugerido": 83992.75,
    "proveedor": "OPENAI",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-22-wix",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-ba5f1976-d121-43c1-a224-201021c027c2",
    "ordenGlobal": 129,
    "nombre": "Wix",
    "obligacion": "Wix",
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Wix",
    "frecuencia": "Anual",
    "diaSugerido": 46164,
    "valorSugerido": 1152000,
    "proveedor": "Wix",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-23-dominio",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-0be0beb2-fd8d-4f11-ac82-0cfbcb31c900",
    "ordenGlobal": 130,
    "nombre": "Dominio",
    "obligacion": "Dominio",
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Dominio",
    "frecuencia": "Anual",
    "diaSugerido": 46152,
    "valorSugerido": 155400,
    "proveedor": "Wix",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-24-google-one-alek",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-1db58b03-4197-4ee3-aa7e-bb77a9874d86",
    "ordenGlobal": 131,
    "nombre": "Google One Alek",
    "obligacion": "Google One Alek",
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Google One Alek",
    "frecuencia": "Mensual",
    "diaSugerido": null,
    "valorSugerido": 79000,
    "proveedor": "Google One",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": false,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-25-google-one-cata",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-5f9a0caa-3eaf-47c6-aa26-a0e752733050",
    "ordenGlobal": 132,
    "nombre": "Google One Cata",
    "obligacion": "Google One Cata",
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Google One Cata",
    "frecuencia": "Mensual",
    "diaSugerido": null,
    "valorSugerido": 79000,
    "proveedor": "Google One",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": false,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-26-google-one-musicala",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-bfa8128e-1a69-4005-848f-b9ccef039248",
    "ordenGlobal": 133,
    "nombre": "Google One Musicala",
    "obligacion": "Google One Musicala",
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Google One Musicala",
    "frecuencia": "Mensual",
    "diaSugerido": null,
    "valorSugerido": 79000,
    "proveedor": "Google One",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-27-star",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-26270a84-821b-4d95-90bc-40c2aeb8ab41",
    "ordenGlobal": 134,
    "nombre": "Star+",
    "obligacion": "Star+",
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Star+",
    "frecuencia": "Mensual",
    "diaSugerido": null,
    "valorSugerido": null,
    "proveedor": "Star+",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-28-keybe",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-76843c99-4610-4e70-87a9-c90a5d836f20",
    "ordenGlobal": 135,
    "nombre": "Keybe",
    "obligacion": "Keybe",
    "categoria": "Software y plataformas digitales",
    "subcategoria": "Keybe",
    "frecuencia": "Mensual",
    "diaSugerido": null,
    "valorSugerido": 163785,
    "proveedor": "Keybe",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": false,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "categoria-seguros-seguros",
    "tipoRegistro": "categoria",
    "origenHoja": "Gastos fijos",
    "ordenGlobal": 136,
    "ordenCategoria": 1027,
    "categoria": "Seguros",
    "subcategoria": "Seguros",
    "nombre": "Seguros",
    "activo": true,
    "visible": true
  },
  {
    "id": "gasto-fijo-29-seguro-general",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-4a4d341a-aa9a-4a45-87f7-dad3182e73ba",
    "ordenGlobal": 137,
    "nombre": "Seguro general",
    "obligacion": "Seguro general",
    "categoria": "Seguros",
    "subcategoria": "Seguros",
    "frecuencia": "Anual",
    "diaSugerido": null,
    "valorSugerido": 576689,
    "proveedor": "Sura",
    "automatico": false,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-30-seguro-general",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-707c320e-12d0-4a39-a991-c066b9843aab",
    "ordenGlobal": 138,
    "nombre": "Seguro general",
    "obligacion": "Seguro general",
    "categoria": "Seguros",
    "subcategoria": "Seguros",
    "frecuencia": "Anual",
    "diaSugerido": null,
    "valorSugerido": 1680993,
    "proveedor": "Sura",
    "automatico": false,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Sede Pasadena",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-31-google-ads",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-1fbad207-fc87-45f7-b0fd-ff28e1dc7fc6",
    "ordenGlobal": 139,
    "nombre": "Google Ads",
    "obligacion": "Google Ads",
    "categoria": "Diseño y publicidad",
    "subcategoria": "Google Ads",
    "frecuencia": "Mensual",
    "diaSugerido": 1,
    "valorSugerido": null,
    "proveedor": "Google Ads",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "categoria-diseno-y-publicidad-meta-ads",
    "tipoRegistro": "categoria",
    "origenHoja": "Gastos fijos",
    "ordenGlobal": 140,
    "ordenCategoria": 1030,
    "categoria": "Diseño y publicidad",
    "subcategoria": "Meta Ads",
    "nombre": "Meta Ads",
    "activo": true,
    "visible": true
  },
  {
    "id": "gasto-fijo-32-meta-ads",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-e3ffd446-aa43-4d3f-a595-85a38a46d429",
    "ordenGlobal": 141,
    "nombre": "Meta Ads",
    "obligacion": "Meta Ads",
    "categoria": "Diseño y publicidad",
    "subcategoria": "Meta Ads",
    "frecuencia": "Mensual",
    "diaSugerido": 1,
    "valorSugerido": null,
    "proveedor": "Meta",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "categoria-diseno-y-publicidad-tiktok-ads",
    "tipoRegistro": "categoria",
    "origenHoja": "Gastos fijos",
    "ordenGlobal": 142,
    "ordenCategoria": 1031,
    "categoria": "Diseño y publicidad",
    "subcategoria": "Tiktok ads",
    "nombre": "Tiktok ads",
    "activo": true,
    "visible": true
  },
  {
    "id": "gasto-fijo-33-tiktok-ads",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-5a1d8019-66d0-4a33-8f4c-830807b0d92f",
    "ordenGlobal": 143,
    "nombre": "Tiktok ads",
    "obligacion": "Tiktok ads",
    "categoria": "Diseño y publicidad",
    "subcategoria": "Tiktok ads",
    "frecuencia": "Mensual",
    "diaSugerido": 1,
    "valorSugerido": null,
    "proveedor": "Tik tok",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "categoria-instrumentos-y-equipos-compra-o-mantenimiento-de-equipos",
    "tipoRegistro": "categoria",
    "origenHoja": "Gastos fijos",
    "ordenGlobal": 144,
    "ordenCategoria": 1032,
    "categoria": "Instrumentos y equipos",
    "subcategoria": "Compra o mantenimiento de equipos",
    "nombre": "Compra o mantenimiento de equipos",
    "activo": true,
    "visible": true
  },
  {
    "id": "gasto-fijo-34-compra-y-mantenimiento-de-nuevos-equipos",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-d8ff8b5b-ca95-4709-82f3-cb16554f743c",
    "ordenGlobal": 145,
    "nombre": "Compra y mantenimiento de nuevos equipos",
    "obligacion": "Compra y mantenimiento de nuevos equipos",
    "categoria": "Instrumentos y equipos",
    "subcategoria": "Compra o mantenimiento de equipos",
    "frecuencia": "Bimensual",
    "diaSugerido": null,
    "valorSugerido": 1000000,
    "proveedor": "",
    "automatico": true,
    "cuentaBancaria": "",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "categoria-arrendamiento-arrendamiento-pasadena",
    "tipoRegistro": "categoria",
    "origenHoja": "Gastos fijos",
    "ordenGlobal": 146,
    "ordenCategoria": 1033,
    "categoria": "Arrendamiento",
    "subcategoria": "Arrendamiento Pasadena",
    "nombre": "Arrendamiento Pasadena",
    "activo": true,
    "visible": true
  },
  {
    "id": "gasto-fijo-35-arrendamiento-pasadena",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "GF-d9969056-6bf8-4299-9685-d8417bdffb29",
    "ordenGlobal": 147,
    "nombre": "Arrendamiento Pasadena",
    "obligacion": "Arrendamiento Pasadena",
    "categoria": "Arrendamiento",
    "subcategoria": "Arrendamiento Pasadena",
    "frecuencia": "Mensual",
    "diaSugerido": null,
    "valorSugerido": 4536291,
    "proveedor": "",
    "automatico": true,
    "cuentaBancaria": "Bancolombia",
    "activo": true,
    "proyecto": "Sede Pasadena",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-36-soraya-castro",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "",
    "ordenGlobal": 148,
    "nombre": "Soraya Castro",
    "obligacion": "Soraya Castro",
    "categoria": "Contabilidad",
    "subcategoria": "Contabilidad",
    "frecuencia": "Mensual",
    "diaSugerido": 46082,
    "valorSugerido": 1091574,
    "proveedor": "Soraya Castro",
    "automatico": false,
    "cuentaBancaria": "Bancolombia",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-fijo-37-safe-mode",
    "tipoRegistro": "gasto_fijo",
    "origenHoja": "Gastos fijos",
    "sourceId": "",
    "ordenGlobal": 149,
    "nombre": "Safe Mode",
    "obligacion": "Safe Mode",
    "categoria": "SG SST",
    "subcategoria": "Safe Mode",
    "frecuencia": "Mensual",
    "diaSugerido": 46082,
    "valorSugerido": 307797.5,
    "proveedor": "Safe Mode",
    "automatico": true,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "retefuenteServicios": "",
    "retencionIca": "",
    "visible": true
  },
  {
    "id": "gasto-variable-2-implementos-de-aseo",
    "tipoRegistro": "gasto_variable",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 150,
    "nombre": "Implementos de aseo",
    "categoria": "Aseo",
    "subcategoria": "Implementos de aseo",
    "frecuencia": "Bimensual",
    "diaSugerido": null,
    "valorSugerido": null,
    "proveedor": "D1",
    "automatico": false,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Sede Pasadena",
    "visible": true
  },
  {
    "id": "gasto-variable-3-impuesto-4x1000",
    "tipoRegistro": "gasto_variable",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 151,
    "nombre": "Impuesto 4x1000",
    "categoria": "Impuestos (predial, etc.)",
    "subcategoria": "Impuesto 4x1000",
    "frecuencia": "Mensual",
    "diaSugerido": null,
    "valorSugerido": null,
    "proveedor": "",
    "automatico": true,
    "cuentaBancaria": "",
    "activo": true,
    "proyecto": "Musicala",
    "visible": true
  },
  {
    "id": "gasto-variable-4-impuesto-iva",
    "tipoRegistro": "gasto_variable",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 152,
    "nombre": "Impuesto IVA",
    "categoria": "Impuestos (predial, etc.)",
    "subcategoria": "Impuesto IVA",
    "frecuencia": "Mensual",
    "diaSugerido": null,
    "valorSugerido": null,
    "proveedor": "DIAN",
    "automatico": true,
    "cuentaBancaria": "",
    "activo": true,
    "proyecto": "Musicala",
    "visible": true
  },
  {
    "id": "gasto-variable-5-impuesto-reteica",
    "tipoRegistro": "gasto_variable",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 153,
    "nombre": "Impuesto Reteica",
    "categoria": "Impuestos (predial, etc.)",
    "subcategoria": "Impuesto Reteica",
    "frecuencia": "Bimensual",
    "diaSugerido": null,
    "valorSugerido": null,
    "proveedor": "DIAN",
    "automatico": false,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "visible": true
  },
  {
    "id": "gasto-variable-6-impuesto-retefuente",
    "tipoRegistro": "gasto_variable",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 154,
    "nombre": "Impuesto Retefuente",
    "categoria": "Impuestos (predial, etc.)",
    "subcategoria": "Impuesto Retefuente",
    "frecuencia": "Mensual",
    "diaSugerido": null,
    "valorSugerido": null,
    "proveedor": "DIAN",
    "automatico": false,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "visible": true
  },
  {
    "id": "gasto-variable-7-ica",
    "tipoRegistro": "gasto_variable",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 155,
    "nombre": "ICA",
    "categoria": "Impuestos (predial, etc.)",
    "subcategoria": "ICA",
    "frecuencia": "Anual",
    "diaSugerido": null,
    "valorSugerido": null,
    "proveedor": "Hacienda",
    "automatico": false,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "visible": true
  },
  {
    "id": "gasto-variable-8-declaracion-de-renta",
    "tipoRegistro": "gasto_variable",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 156,
    "nombre": "Declaración de renta",
    "categoria": "Impuestos (predial, etc.)",
    "subcategoria": "Declaración de renta",
    "frecuencia": "Anual",
    "diaSugerido": null,
    "valorSugerido": null,
    "proveedor": "Hacienda",
    "automatico": false,
    "cuentaBancaria": "Tarjeta C A",
    "activo": true,
    "proyecto": "Musicala",
    "visible": true
  },
  {
    "id": "categoria-otros-gastos-especifique-papeleria",
    "tipoRegistro": "categoria",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 157,
    "ordenCategoria": 1007,
    "categoria": "Otros gastos (especifique)",
    "subcategoria": "Papelería",
    "nombre": "Papelería",
    "activo": true,
    "visible": true
  },
  {
    "id": "gasto-variable-9-papeleria",
    "tipoRegistro": "gasto_variable",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 158,
    "nombre": "Papelería",
    "categoria": "Otros gastos (especifique)",
    "subcategoria": "Papelería",
    "frecuencia": "Mensual",
    "diaSugerido": null,
    "valorSugerido": null,
    "proveedor": "",
    "automatico": true,
    "cuentaBancaria": "",
    "activo": true,
    "proyecto": "Sede Pasadena",
    "visible": true
  },
  {
    "id": "categoria-otros-gastos-especifique-materiales-artes",
    "tipoRegistro": "categoria",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 159,
    "ordenCategoria": 1008,
    "categoria": "Otros gastos (especifique)",
    "subcategoria": "Materiales artes",
    "nombre": "Materiales artes",
    "activo": true,
    "visible": true
  },
  {
    "id": "gasto-variable-10-materiales-artes",
    "tipoRegistro": "gasto_variable",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 160,
    "nombre": "Materiales artes",
    "categoria": "Otros gastos (especifique)",
    "subcategoria": "Materiales artes",
    "frecuencia": "Mensual",
    "diaSugerido": null,
    "valorSugerido": null,
    "proveedor": "",
    "automatico": true,
    "cuentaBancaria": "",
    "activo": true,
    "proyecto": "Sede Pasadena",
    "visible": true
  },
  {
    "id": "gasto-variable-11-papeleria",
    "tipoRegistro": "gasto_variable",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 161,
    "nombre": "Papelería",
    "categoria": "Otros gastos (especifique)",
    "subcategoria": "Papelería",
    "frecuencia": "Mensual",
    "diaSugerido": null,
    "valorSugerido": null,
    "proveedor": "",
    "automatico": true,
    "cuentaBancaria": "",
    "activo": true,
    "proyecto": "FSA",
    "visible": true
  },
  {
    "id": "gasto-variable-12-materiales-artes",
    "tipoRegistro": "gasto_variable",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 162,
    "nombre": "Materiales artes",
    "categoria": "Otros gastos (especifique)",
    "subcategoria": "Materiales artes",
    "frecuencia": "Mensual",
    "diaSugerido": null,
    "valorSugerido": null,
    "proveedor": "",
    "automatico": true,
    "cuentaBancaria": "",
    "activo": true,
    "proyecto": "FSA",
    "visible": true
  },
  {
    "id": "gasto-variable-13-dotacion",
    "tipoRegistro": "gasto_variable",
    "origenHoja": "Gastos variables",
    "ordenGlobal": 163,
    "nombre": "Dotación",
    "categoria": "Nómina",
    "subcategoria": "Dotación",
    "frecuencia": "Trimestral",
    "diaSugerido": null,
    "valorSugerido": null,
    "proveedor": "",
    "automatico": true,
    "cuentaBancaria": "",
    "activo": true,
    "proyecto": "",
    "visible": true
  },
  {
    "id": "categoria-salarios-docentes-prestacion-salarios-docentes-prestacion",
    "tipoRegistro": "categoria",
    "origenHoja": "Proveedores",
    "ordenGlobal": 164,
    "ordenCategoria": 1000,
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "nombre": "Salarios Docentes prestación",
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-2-angie-natalia-nitola",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 165,
    "nombre": "Angie Natalia Nitola",
    "proveedor": "Angie Natalia Nitola",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 415297,
    "valorFinal": 411285.231,
    "mesTexto": "Enero",
    "periodo": "2026-01",
    "diaSugeridoIso": "2026-02-01",
    "reteIca": 4011.76902,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-3-cesar-alvarez",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 166,
    "nombre": "César Alvarez",
    "proveedor": "César Alvarez",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 115000,
    "valorFinal": 115000,
    "mesTexto": "Enero",
    "periodo": "2026-01",
    "diaSugeridoIso": "2026-02-01",
    "reteIca": 0,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "categoria-aseo-nancy-caballero-moreno",
    "tipoRegistro": "categoria",
    "origenHoja": "Proveedores",
    "ordenGlobal": 167,
    "ordenCategoria": 1002,
    "categoria": "Aseo",
    "subcategoria": "Nancy Caballero Moreno",
    "nombre": "Nancy Caballero Moreno",
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-4-nancy-caballero-moreno",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 168,
    "nombre": "Nancy Caballero Moreno",
    "proveedor": "Nancy Caballero Moreno",
    "categoria": "Aseo",
    "subcategoria": "Nancy Caballero Moreno",
    "valorCuentaCobro": 984000,
    "valorFinal": 974494.56,
    "mesTexto": "Enero",
    "periodo": "2026-01",
    "diaSugeridoIso": "2026-02-01",
    "reteIca": 9505.44,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-5-soraya-castro",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 169,
    "nombre": "Soraya Castro",
    "proveedor": "Soraya Castro",
    "categoria": "Contabilidad",
    "subcategoria": "Contabilidad",
    "valorCuentaCobro": 1100000,
    "valorFinal": 1091574,
    "mesTexto": "Marzo",
    "periodo": "2026-03",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 10626,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-6-angie-natalia-nitola",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 170,
    "nombre": "Angie Natalia Nitola",
    "proveedor": "Angie Natalia Nitola",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 924980,
    "valorFinal": 916044.6932,
    "mesTexto": "Febrero",
    "periodo": "2026-02",
    "diaSugeridoIso": "2026-03-01",
    "reteIca": 8935.3068,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-7-nancy-caballero-moreno",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 171,
    "nombre": "Nancy Caballero Moreno",
    "proveedor": "Nancy Caballero Moreno",
    "categoria": "Aseo",
    "subcategoria": "Nancy Caballero Moreno",
    "valorCuentaCobro": 984000,
    "valorFinal": 974494.56,
    "mesTexto": "Febrero",
    "periodo": "2026-02",
    "diaSugeridoIso": "2026-03-01",
    "reteIca": 9505.44,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-8-david-felipe-lindo",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 172,
    "nombre": "David Felipe Lindo",
    "proveedor": "David Felipe Lindo",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 200000,
    "valorFinal": 198068,
    "mesTexto": "Febrero",
    "periodo": "2026-02",
    "diaSugeridoIso": "2026-03-01",
    "reteIca": 1932,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-9-juan-pablo-pico-santos",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 173,
    "nombre": "Juan Pablo Pico Santos",
    "proveedor": "Juan Pablo Pico Santos",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 324000,
    "valorFinal": 320870.16,
    "mesTexto": "Febrero",
    "periodo": "2026-02",
    "diaSugeridoIso": "2026-03-01",
    "reteIca": 3129.84,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-10-lizeth-soto-guevara",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 174,
    "nombre": "Lizeth Soto Guevara",
    "proveedor": "Lizeth Soto Guevara",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 100000,
    "valorFinal": 100000,
    "mesTexto": "Febrero",
    "periodo": "2026-02",
    "diaSugeridoIso": "2026-03-01",
    "reteIca": 0,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-11-maria-alejandra-gomez-rueda",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 175,
    "nombre": "María Alejandra Gómez Rueda",
    "proveedor": "María Alejandra Gómez Rueda",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 216000,
    "valorFinal": 213913.44,
    "mesTexto": "Febrero",
    "periodo": "2026-02",
    "diaSugeridoIso": "2026-03-01",
    "reteIca": 2086.56,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-12-soraya-castro",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 176,
    "nombre": "Soraya Castro",
    "proveedor": "Soraya Castro",
    "categoria": "Contabilidad",
    "subcategoria": "Contabilidad",
    "valorCuentaCobro": 1100000,
    "valorFinal": 1091574,
    "mesTexto": "Marzo",
    "periodo": "2026-03",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 10626,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-13-angie-natalia-nitola",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 177,
    "nombre": "Angie Natalia Nitola",
    "proveedor": "Angie Natalia Nitola",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 933465,
    "valorFinal": 924447.7281,
    "mesTexto": "Marzo",
    "periodo": "2026-03",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 9017.2719,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-14-nancy-caballero-moreno",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 178,
    "nombre": "Nancy Caballero Moreno",
    "proveedor": "Nancy Caballero Moreno",
    "categoria": "Aseo",
    "subcategoria": "Nancy Caballero Moreno",
    "valorCuentaCobro": 984000,
    "valorFinal": 974494.56,
    "mesTexto": "Marzo",
    "periodo": "2026-03",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 9505.44,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-15-david-felipe-lindo",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 179,
    "nombre": "David Felipe Lindo",
    "proveedor": "David Felipe Lindo",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 80000,
    "valorFinal": 80000,
    "mesTexto": "Marzo",
    "periodo": "2026-03",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 0,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-16-juan-pablo-pico-santos",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 180,
    "nombre": "Juan Pablo Pico Santos",
    "proveedor": "Juan Pablo Pico Santos",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 180000,
    "valorFinal": 178261.2,
    "mesTexto": "Marzo",
    "periodo": "2026-03",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 1738.8,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-17-lizeth-soto-guevara",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 181,
    "nombre": "Lizeth Soto Guevara",
    "proveedor": "Lizeth Soto Guevara",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 90000,
    "valorFinal": 90000,
    "mesTexto": "Marzo",
    "periodo": "2026-03",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 0,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-18-maria-alejandra-gomez-rueda",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 182,
    "nombre": "María Alejandra Gómez Rueda",
    "proveedor": "María Alejandra Gómez Rueda",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 396000,
    "valorFinal": 392174.64,
    "mesTexto": "Marzo",
    "periodo": "2026-03",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 3825.36,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-19-brian-alexander-gutierrez-mahecha",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 183,
    "nombre": "Brian Alexander Gutiérrez Mahecha",
    "proveedor": "Brian Alexander Gutiérrez Mahecha",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 320000,
    "valorFinal": 316908.8,
    "mesTexto": "Marzo",
    "periodo": "2026-03",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 3091.2,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-20-tania-isabel-gomez-gomez",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 184,
    "nombre": "Tania Isabel Gómez Gómez",
    "proveedor": "Tania Isabel Gómez Gómez",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 30000,
    "valorFinal": 30000,
    "mesTexto": "Marzo",
    "periodo": "2026-03",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 0,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-21-soraya-castro",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 185,
    "nombre": "Soraya Castro",
    "proveedor": "Soraya Castro",
    "categoria": "Contabilidad",
    "subcategoria": "Contabilidad",
    "valorCuentaCobro": 1100000,
    "valorFinal": 1091574,
    "mesTexto": "Marzo",
    "periodo": "2026-03",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 10626,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-22-safe-mode",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 186,
    "nombre": "Safe Mode",
    "proveedor": "Safe Mode",
    "categoria": "SG SST",
    "subcategoria": "Safe Mode",
    "valorCuentaCobro": 315350,
    "valorFinal": 307797.5,
    "mesTexto": "Marzo",
    "periodo": "2026-03",
    "diaSugeridoIso": "2026-04-02",
    "reteIca": 3046.281,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-23-nancy-caballero-moreno",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 187,
    "nombre": "Nancy Caballero Moreno",
    "proveedor": "Nancy Caballero Moreno",
    "categoria": "Aseo",
    "subcategoria": "Nancy Caballero Moreno",
    "valorCuentaCobro": 984000,
    "valorFinal": 974494.56,
    "mesTexto": "abril",
    "periodo": "2026-04",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 9505.44,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-24-david-felipe-lindo",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 188,
    "nombre": "David Felipe Lindo",
    "proveedor": "David Felipe Lindo",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 160000,
    "valorFinal": 160000,
    "mesTexto": "abril",
    "periodo": "2026-04",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 0,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-25-juan-pablo-pico-santos",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 189,
    "nombre": "Juan Pablo Pico Santos",
    "proveedor": "Juan Pablo Pico Santos",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 180000,
    "valorFinal": 178261.2,
    "mesTexto": "abril",
    "periodo": "2026-04",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 1738.8,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-26-maria-alejandra-gomez-rueda",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 190,
    "nombre": "María Alejandra Gómez Rueda",
    "proveedor": "María Alejandra Gómez Rueda",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 324000,
    "valorFinal": 320870.16,
    "mesTexto": "abril",
    "periodo": "2026-04",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 3129.84,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-27-soraya-castro",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 191,
    "nombre": "Soraya Castro",
    "proveedor": "Soraya Castro",
    "categoria": "Contabilidad",
    "subcategoria": "Contabilidad",
    "valorCuentaCobro": 1100000,
    "valorFinal": 1091574,
    "mesTexto": "abril",
    "periodo": "2026-04",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 10626,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-28-cesar-alvarez",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 192,
    "nombre": "César Alvarez",
    "proveedor": "César Alvarez",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 132000,
    "valorFinal": 132000,
    "mesTexto": "abril",
    "periodo": "2026-04",
    "diaSugeridoIso": "2026-02-01",
    "reteIca": 0,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-29-lizeth-soto-guevara",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 193,
    "nombre": "Lizeth Soto Guevara",
    "proveedor": "Lizeth Soto Guevara",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 90000,
    "valorFinal": 90000,
    "mesTexto": "abril",
    "periodo": "2026-04",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 0,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-30-brian-alexander-gutierrez-mahecha",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 194,
    "nombre": "Brian Alexander Gutiérrez Mahecha",
    "proveedor": "Brian Alexander Gutiérrez Mahecha",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 176000,
    "valorFinal": 174299.84,
    "mesTexto": "abril",
    "periodo": "2026-04",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 1700.16,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-31-angie-natalia-nitola",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 195,
    "nombre": "Angie Natalia Nitola",
    "proveedor": "Angie Natalia Nitola",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 1117120,
    "valorFinal": 1106328.621,
    "mesTexto": "abril",
    "periodo": "2026-04",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 10791.3792,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-32-natalia-moreno",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 196,
    "nombre": "Natalia Moreno",
    "proveedor": "Natalia Moreno",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 336000,
    "valorFinal": 332754.24,
    "mesTexto": "abril",
    "periodo": "2026-04",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 3245.76,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-33-eryck-martinez",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 197,
    "nombre": "Eryck Martinez",
    "proveedor": "Eryck Martinez",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 324000,
    "valorFinal": 320870.16,
    "mesTexto": "abril",
    "periodo": "2026-04",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 3129.84,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-34-tania-isabel-gomez-gomez",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 198,
    "nombre": "Tania Isabel Gómez Gómez",
    "proveedor": "Tania Isabel Gómez Gómez",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 60000,
    "valorFinal": 60000,
    "mesTexto": "abril",
    "periodo": "2026-04",
    "diaSugeridoIso": "2026-04-01",
    "reteIca": 0,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-35-nancy-caballero-moreno",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 199,
    "nombre": "Nancy Caballero Moreno",
    "proveedor": "Nancy Caballero Moreno",
    "categoria": "Aseo",
    "subcategoria": "Nancy Caballero Moreno",
    "valorCuentaCobro": 984000,
    "valorFinal": 974494.56,
    "mesTexto": "Mayo",
    "periodo": "2026-05",
    "diaSugeridoIso": "2026-05-01",
    "reteIca": 9505.44,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-36-maria-alejandra-gomez-rueda",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 200,
    "nombre": "María Alejandra Gómez Rueda",
    "proveedor": "María Alejandra Gómez Rueda",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 360000,
    "valorFinal": 356522.4,
    "mesTexto": "Mayo",
    "periodo": "2026-05",
    "diaSugeridoIso": "2026-05-01",
    "reteIca": 3477.6,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-37-soraya-castro",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 201,
    "nombre": "Soraya Castro",
    "proveedor": "Soraya Castro",
    "categoria": "Contabilidad",
    "subcategoria": "Contabilidad",
    "valorCuentaCobro": 1100000,
    "valorFinal": 1091574,
    "mesTexto": "Mayo",
    "periodo": "2026-05",
    "diaSugeridoIso": "2026-05-01",
    "reteIca": 10626,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-38-natalia-moreno",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 202,
    "nombre": "Natalia Moreno",
    "proveedor": "Natalia Moreno",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 784000,
    "valorFinal": 776426.56,
    "mesTexto": "Mayo",
    "periodo": "2026-05",
    "diaSugeridoIso": "2026-05-01",
    "reteIca": 7573.44,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-39-juan-pablo-pico-santos",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 203,
    "nombre": "Juan Pablo Pico Santos",
    "proveedor": "Juan Pablo Pico Santos",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 356000,
    "valorFinal": 352561.04,
    "mesTexto": "Mayo",
    "periodo": "2026-05",
    "diaSugeridoIso": "2026-05-01",
    "reteIca": 3438.96,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-40-angie-natalia-nitola",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 204,
    "nombre": "Angie Natalia Nitola",
    "proveedor": "Angie Natalia Nitola",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 1057120,
    "valorFinal": 1046908.221,
    "mesTexto": "Mayo",
    "periodo": "2026-05",
    "diaSugeridoIso": "2026-05-01",
    "reteIca": 10211.7792,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-41-eryck-martinez",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 205,
    "nombre": "Eryck Martinez",
    "proveedor": "Eryck Martinez",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 416000,
    "valorFinal": 411981.44,
    "mesTexto": "Mayo",
    "periodo": "2026-05",
    "diaSugeridoIso": "2026-05-01",
    "reteIca": 4018.56,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-44-lizeth-soto-guevara",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 206,
    "nombre": "Lizeth Soto Guevara",
    "proveedor": "Lizeth Soto Guevara",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 90000,
    "valorFinal": 90000,
    "mesTexto": "Mayo",
    "periodo": "2026-05",
    "diaSugeridoIso": "2026-05-01",
    "reteIca": 0,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-46-dara-natalia-cifuentes-rojas",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 207,
    "nombre": "Dara Natalia Cifuentes Rojas",
    "proveedor": "Dara Natalia Cifuentes Rojas",
    "categoria": "",
    "subcategoria": "",
    "valorCuentaCobro": 108000,
    "valorFinal": 108000,
    "mesTexto": "Mayo",
    "periodo": "2026-05",
    "diaSugeridoIso": "2026-05-01",
    "reteIca": 0,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "proveedor-48-cesar-alvarez",
    "tipoRegistro": "proveedor",
    "origenHoja": "Proveedores",
    "ordenGlobal": 208,
    "nombre": "César Alvarez",
    "proveedor": "César Alvarez",
    "categoria": "Salarios Docentes prestación",
    "subcategoria": "Salarios Docentes prestación",
    "valorCuentaCobro": 74000,
    "valorFinal": 74000,
    "mesTexto": "Mayo",
    "periodo": "2026-05",
    "diaSugeridoIso": "2026-05-01",
    "reteIca": 0,
    "reteFuente": 0,
    "activo": true,
    "visible": true
  },
  {
    "id": "movimiento-2-egr-2026-0001",
    "tipoRegistro": "movimiento",
    "origenHoja": "Movimientos",
    "sourceId": "",
    "ordenGlobal": 209,
    "consecutivo": "EGR-2026-0001",
    "fechaIso": "2026-01-05",
    "categoria": "Bancarios",
    "proveedor": "Bancolombia",
    "concepto": "Cuota de manejo Bancolombia",
    "detalle": "Cuota Bancolombia",
    "valor": 55472,
    "medioPago": "Bancolombia",
    "estado": "Pagado",
    "responsable": "",
    "proyecto": "",
    "soporteUrl": "",
    "factura": "",
    "comprobante": "",
    "fechaPagoIso": "",
    "creadoEnLibro": "",
    "actualizadoEnLibro": "",
    "activo": true,
    "visible": true
  },
  {
    "id": "movimiento-3-egr-2026-0002",
    "tipoRegistro": "movimiento",
    "origenHoja": "Movimientos",
    "sourceId": "",
    "ordenGlobal": 210,
    "consecutivo": "EGR-2026-0002",
    "fechaIso": "2026-02-03",
    "categoria": "Contabilidad",
    "proveedor": "In-plementar",
    "concepto": "Contabilidad",
    "detalle": "Contabilidad",
    "valor": 2139148,
    "medioPago": "Bancolombia",
    "estado": "Pagado",
    "responsable": "",
    "proyecto": "",
    "soporteUrl": "",
    "factura": "",
    "comprobante": "",
    "fechaPagoIso": "",
    "creadoEnLibro": "",
    "actualizadoEnLibro": "",
    "activo": true,
    "visible": true
  },
  {
    "id": "movimiento-4-egr-2026-0003",
    "tipoRegistro": "movimiento",
    "origenHoja": "Movimientos",
    "sourceId": "",
    "ordenGlobal": 211,
    "consecutivo": "EGR-2026-0003",
    "fechaIso": "2026-01-03",
    "categoria": "Servicios generales",
    "proveedor": "Nancy Caballero Moreno",
    "concepto": "Aseo",
    "detalle": "Pago proveedores",
    "valor": 965581,
    "medioPago": "Bancolombia",
    "estado": "Pagado",
    "responsable": "",
    "proyecto": "",
    "soporteUrl": "",
    "factura": "",
    "comprobante": "",
    "fechaPagoIso": "",
    "creadoEnLibro": "",
    "actualizadoEnLibro": "",
    "activo": true,
    "visible": true
  },
  {
    "id": "movimiento-5-egr-2026-0004",
    "tipoRegistro": "movimiento",
    "origenHoja": "Movimientos",
    "sourceId": "",
    "ordenGlobal": 212,
    "consecutivo": "EGR-2026-0004",
    "fechaIso": "2026-02-03",
    "categoria": "Servicios públicos",
    "proveedor": "Enel Codensa",
    "concepto": "Enel Codensa",
    "detalle": "Enel Codensa",
    "valor": 779470,
    "medioPago": "Bancolombia",
    "estado": "Pagado",
    "responsable": "",
    "proyecto": "",
    "soporteUrl": "",
    "factura": "",
    "comprobante": "",
    "fechaPagoIso": "",
    "creadoEnLibro": "",
    "actualizadoEnLibro": "",
    "activo": true,
    "visible": true
  }
];
